name: movie_app_clean_architecture_mvvm
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.2
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  lottie: ^1.2.1
  provider: ^6.0.2
  retrofit: ^3.0.1

dev_dependencies:
  build_runner: 2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  lint: ^1.0.0
  retrofit_generator: ^3.0.1+1

flutter:
  uses-material-design: true

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iransansregular.ttf
        - asset: assets/fonts/iransansbold.ttf
          weight: 700
