name: movie_app_clean_architecture_mvvm
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  json_serializable: ^6.1.3
  lottie: ^1.2.1
  provider: ^6.0.2
  retrofit: ^3.0.1

dev_dependencies:
  build_runner: 2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^3.0.1+1
  lint: ^1.0.0

flutter:
  uses-material-design: true
